config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView 

from debug_toolbar.toolbar import debug_toolbar_urls


admin.site.site_header = "Energy Unit's Admin"

urlpatterns = [
    path('admin/', admin.site.urls),

    path(
        '', 
         TemplateView.as_view(template_name='index.html'), 
         name='main_page'
         ),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('work_tower/', include(('work_tower.urls', 'work_tower'), namespace='work_tower')),
    path('task/', include(('task.urls', 'task'), namespace='task')),
    path('workflow/', include(('workflow.urls', 'workflow'), namespace='workflow'),
         ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
  + debug_toolbar_urls()

task/urls.py
from django.urls import path
from .views import (
    DoerTasksListView,
    TaskStatusUpdateView,
    
    get_archived_tasks_view,
    )


app_name = "task"

urlpatterns = [
    path(
        'doer_tasks/<int:doer_id>/', 
        DoerTasksListView.as_view(), 
        name='doer_tasks'
        ),
    path(
        'task_update_status/<int:pk>/', 
        TaskStatusUpdateView.as_view(), 
        name='task_update_status',
        ),
    path('get_archived_tasks/', get_archived_tasks_view, name='get_archived_tasks'),

]

work_tower/urls.py
from django.urls import path
from django.views.generic import TemplateView 

from work_tower.views.substation import substations_list_view
from work_tower.views.mcc import substation_mccs_view, mcc_nodes_view
from work_tower.views.node import (
    nodes_list_view, 
    motors_list_view, 
    create_node_motor_view, 
    create_node_view, 
    node_detail_view, 
    show_created_node_view, 
    show_created_node_motor_view, 
    get_level_nodes_view, 
    pre_change_data_view, 
    search_node_view, 
    update_node_motor_view, 
    update_node_view, 
    delete_motor_view, 
    delete_node_view,
)      


app_name = 'work_tower'

urlpatterns = [
    path('', substations_list_view, name='substations'),
    path('substation/<slug:substation_slug>/', substation_mccs_view, name='substation_mccs'),
    path('mcc/<slug:mcc_slug>/', mcc_nodes_view, name='mcc_detail'),

    path('node_list/', nodes_list_view, name='node_list'),
    path('motor_list/', motors_list_view, name='motors_list'),

    path('create_node_motor/', create_node_motor_view, name='create_node_motor'),
    path('create_node/', create_node_view, name='create_node'),

    path('show_created_node/', show_created_node_view, name='show_created_node'),
    path('show_created_node_motor/', show_created_node_motor_view, name='show_created_node_motor'),

    path('get_level_nodes/', get_level_nodes_view, name='get_level_nodes'),

    path('node/<int:node_id>/', node_detail_view, name='node_detail'),
    path('pre_change_data/', pre_change_data_view, name='pre_change_data'),

    path('search_node/', search_node_view, name='search_node'),
    path('update_motor/', update_node_motor_view, name='update_motor'),
    path('update_node/', update_node_view, name='update_node'),
    path(
        'updated_motor_message/', 
         TemplateView.as_view(template_name='work_tower/messages/updated_motor_message.html'), 
         name='updated_motor_message'
         ),
    path(
        'updated_node_message/', 
         TemplateView.as_view(template_name='work_tower/messages/updated_node_message.html'), 
         name='updated_node_message'
         ),

    path('delete_motor/', delete_motor_view, name='delete_motor'),
    path('delete_node/', delete_node_view, name='delete_node'),
    path(
        'deleted_motor_message/', 
         TemplateView.as_view(template_name='work_tower/messages/deleted_motor_message.html'), 
         name='deleted_motor_message'
         ),
    path(
        'deleted_node_message/', 
         TemplateView.as_view(template_name='work_tower/messages/deleted_node_message.html'), 
         name='deleted_node_message'
         ),
]

workflow/urls.py
from django.urls import path 

from .views import (
    create_task_assignment_view, 
    get_task_doers_view,
    get_doer_tasks_view,
    )

app_name = "workflow"

urlpatterns = [
    path(
        'create_task_assignment/', 
        create_task_assignment_view, 
        name="create_task_assignment",
        ), 
    path(
        'task_doers_list/', 
        get_task_doers_view, 
        name="task_doers_list",
        ), 
    path(
        'doer_tasks/<int:doer_id>/', 
        get_doer_tasks_view, 
        name="doer_tasks",
        ),
    ]

templates/partials/header.html
<h2 class="text-dark mr-5">Відділ Головного Енергетика</h2>
            
<div class="d-flex ml-5">
    {% if employee %}
        <h5 class="justify-content-end">
            <a href="{{ employee_profile_url }}" 
            class="p-1 m-1 border-dark fw-bold text-primary">
                {{ user.first_name }} {{ user.last_name }}
            </a> | <a href="{{ employee_logout_url }}">Вийти</a>
        </h5>
    {% else %}
        <h5 class="m-auto">
            <a href="{{ employee_login_url }}">Увійти</a> | <a href="{{ employee_register_url }}">Реєстрація</a>
        </h5>
    {% endif %}

    <p class="position-relative top-50 end-0 p-1 border-dark 
            border border-2 rounded fw-bold text-primary m-1">
        <a href="{% url 'main_page' %}" type="button">
            На головну
        </a>
    </p>
    
</div>

templates/partials/navbar.html
<ul class="list-unstyled m-1 d-flex">
    
    {% if user.is_authenticated %} 
        <li>
            <a href="{% url 'work_tower:substations' %}"  
            class="fw-bold text-white border border-dark p-2 mx-3 rounded fs-5">
                Підстанції
            </a>
        </li>

        <li>
            <a href="{% url 'work_tower:search_node' %}"  
            class="fw-bold text-white border border-dark p-2 mx-3 rounded fs-5">
                Знайти вузол
            </a>
        </li>

        <li>
            <a href="{% url 'work_tower:get_level_nodes' %}"  
            class="fw-bold text-white border border-dark p-2 mx-3 rounded fs-5">
            Вузли на відмітці
            </a>
        </li>

        <li>
            <a href="{% url 'work_tower:motors_list' %}"  
            class="fw-bold text-white border border-dark p-2 mx-3 rounded fs-5">
                Список двигунів
            </a>
        </li>
        
        {% if employee.role == 'Engineer' %} 
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle border border-dark" type="button" 
                        id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                    Опції інженера
                </button>
                    
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <li>
                        <a class="dropdown-item" href="{% url 'work_tower:pre_change_data' %}">
                            Додати/Оновити/Видалити двигун/вузол
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'workflow:task_doers_list' %}">
                            Список електриків
                        </a> 
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'workflow:create_task_assignment' %}">
                            Створити завдання
                        </a> 
                    </li> 
                </ul>
            </div>
        {% elif employee.role == 'Electrician' %} 
            <li>
                <a class="btn btn-dark px-3" type="button"
                   href="{% url 'task:doer_tasks' doer_id=employee.id %}">
                    Завдання {{ employee.first_name }} {{ employee.last_name }}
                </a> 
            </li>
        {% endif %} 
        
    {% endif %} 
</ul>

templates/partials/paginator.html
<div class="pagination bg-info m-auto p-1 d-flex justify-content-center align-items-center w-50 rounded shadow">
    <span class="step-links">
        <span class="current text-dark p-2 m-2 rounded" style="font-weight: bold;">
            Сторінка {{ page_obj.number }} із {{ page_obj.paginator.num_pages }}
        </span>
        <div class="d-flex">
        {% if page_obj.has_previous %}
            <h5><a href="?page=1">&laquo; ⏪</a>
            <a href="?page={{ page_obj.previous_page_number }}"> &#x27FD;</a></h5>
        {% endif %}

        {% if page_obj.has_next %}
            <h5><a href="?page={{ page_obj.next_page_number }}">&#x27FF;</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">⏭ &raquo;</a></h5>
        {% endif %}
        </div>
    </span>
</div>

templates/partials/window_history_back.html
<div class="col-md-6 mt-2">
    <button onclick="window.history.back();" class="rounded">&larr; НАЗАД</button>
</div>