config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView 

from debug_toolbar.toolbar import debug_toolbar_urls


admin.site.site_header = "Energy Unit's Admin"

urlpatterns = [
    path('admin/', admin.site.urls),

    path(
        '', 
         TemplateView.as_view(template_name='index.html'), 
         name='main_page'
         ),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('work_tower/', include(('work_tower.urls', 'work_tower'), namespace='work_tower')),
    path('task/', include(('task.urls', 'task'), namespace='task')),
    path('workflow/', include(('workflow.urls', 'workflow'), namespace='workflow'),
         ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
  + debug_toolbar_urls()

task/urls.py
from django.urls import path
from .views import (
    DoerTasksListView,
    TaskStatusUpdateView,
    
    get_archived_tasks_view,
    )


app_name = "task"

urlpatterns = [
    path(
        'doer_tasks/<int:doer_id>/', 
        DoerTasksListView.as_view(), 
        name='doer_tasks'
        ),
    path(
        'task_update_status/<int:pk>/', 
        TaskStatusUpdateView.as_view(), 
        name='task_update_status',
        ),
    path('get_archived_tasks/', get_archived_tasks_view, name='get_archived_tasks'),

]

users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordChangeDoneView

from .views import ( 
    user_login_view,
    user_logout_view,
    user_mobile_update_view,
    reset_password_view,
    delete_user_view,
    check_user_view,
    verify_code_view
    )

from .employee_views import ( 
    employee_register_view,
    employee_profile_view,
    get_electricians_view,
    update_employee_admission_group_view, 
    )


app_name = 'users'

urlpatterns = [
    path('register/', employee_register_view, name='register'),
    path('login/', user_login_view, name='login'),
    path('logout/', user_logout_view, name='logout'),

    path('employee_profile/<int:employee_id>/', employee_profile_view, name='employee_profile'),
    path('update_mobile/', user_mobile_update_view, name='update_mobile'),
    path('reset_password/', reset_password_view, name='reset_password'),
    path(
        'password_change_done/', 
         PasswordChangeDoneView.as_view(template_name='users/registration/password_change_done.html'), 
         name='password_change_done'
         ),

    path('delete_account/', delete_user_view, name='delete_account'),

    path('electricians_list', get_electricians_view, name='electricians_list'),

    path(
        'update-admission-group/<int:employee_id>/', 
        update_employee_admission_group_view, 
        name='update_admission_group'),

    path('check_user/', check_user_view, name='check_user'),
    path('verify_code/', verify_code_view, name='verify_code'),
]

workflow/urls.py
from django.urls import path 

from .views import (
    create_task_assignment_view, 
    get_task_doers_view,
    get_doer_tasks_view,
    )

app_name = "workflow"

urlpatterns = [
    path(
        'create_task_assignment/', 
        create_task_assignment_view, 
        name="create_task_assignment",
        ), 
    path(
        'task_doers_list/', 
        get_task_doers_view, 
        name="task_doers_list",
        ), 
    path(
        'doer_tasks/<int:doer_id>/', 
        get_doer_tasks_view, 
        name="doer_tasks",
        ),
    ]

task/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings

from datetime import datetime, timezone


class Task(models.Model):
    """The model describes servicing instance"""

    class TaskStatus(models.TextChoices):
        PENDING = 'PE', _('Призупинено')
        IN_PROGRESS = 'IP', _('На виконанні')
        COMPLETED = 'CO', _('Закінчено')
        CANCELED = 'CE', _('Скасовано')

    doer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='tasks',
    )
    task_description = models.TextField(default="Завдання не поставлено.")
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(
        blank=True, 
        null=True, 
    )
    status = models.CharField(
        max_length=2,
        choices=TaskStatus.choices,
        default=TaskStatus.IN_PROGRESS
    )

    class Meta:
        ordering = ['-created_at'] 
        verbose_name = _('task')
        verbose_name_plural = _('tasks')

    def __str__(self):
        return f'Завдання N{self.id}: {self.task_description}'
    
    def check_deadline_validity(self):
        """Set deadline to null if it's past or equal to the current time."""
        if self.deadline and self.deadline < datetime.now(timezone.utc):
            self.deadline = None
            self.save()


class TaskArchive(models.Model):
    """Archived Task model."""
    task_id = models.IntegerField()  
    doer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='archived_tasks'
    )
    task_description = models.TextField()
    created_at = models.DateTimeField()
    deadline = models.DateTimeField(blank=True, null=True)
    archived_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"Task N{self.task_id} archived at {str(self.archived_at)[:19]}"

workflow/models.py
from django.db import models
from work_tower.models.node import Node


class TaskAssignment(models.Model):
    """Represents the task assignment linking Task and Node instances."""
    task = models.ForeignKey(
        'task.Task', 
        on_delete=models.CASCADE, 
        related_name='assignments',
        )
    node = models.ForeignKey(
        Node, 
        on_delete=models.CASCADE, 
        related_name='assignments', 
        null=True, blank=True,
        )

workflow/forms.py
from django import forms
from django.utils.timezone import now, timedelta

from task.validators import validate_minimum_one_hour_later
from task.models import Task
from work_tower.models.node import Node
from .models import TaskAssignment
from users.models import Employee


class TaskAssignmentForm(forms.ModelForm):
    """Form to assign a task to a specific doer."""
    doer = forms.ModelChoiceField(
        queryset=Employee.objects.filter(role='Electrician'), 
        label="Виконавець:"
        )
    task_description = forms.CharField(
        widget=forms.Textarea, 
        label="Завдання:"
        )
    node = forms.ModelChoiceField(
        queryset=Node.objects.all(),
        required=False, label="Індекс вузла:"
        )
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        required=False, label="Виконати до:",
        validators=[validate_minimum_one_hour_later]
        )

    class Meta:
        model = TaskAssignment
        fields = ['doer', 'task_description', 'node', 'deadline']

    def save(self, commit=True):
        """Create a Task instance"""

        doer = self.cleaned_data['doer']
        task_description = self.cleaned_data['task_description']
        deadline = self.cleaned_data.get('deadline') or now() + timedelta(days=1)

        task = Task.objects.create(
            doer=doer,
            task_description=task_description,
            deadline=deadline
        )
        task_assignment = TaskAssignment(
            task=task,
            node=self.cleaned_data.get('node')
        )
        if commit:
            task_assignment.save()
        
        return task_assignment

workflow/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth import get_user_model

from .forms import TaskAssignmentForm
from users.models import Employee
from task.models import Task


def create_task_assignment_view(request):
    """Creates a new task assignment."""
    if request.method == 'POST':
        form = TaskAssignmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('workflow:task_doers_list') 
    else:
        form = TaskAssignmentForm()
    context = {
        'form': form,
        'title': 'Створи завдання',
        }
    return render(
        request, 
        'workflow/create_task_assignment.html', 
        context,
        )


def get_task_doers_view(request):
    """
    Displays a paginated list of Employee instances whose role is electricians. If an error occurs while
    fetching motors or pagination fails, the error is handled gracefully.
    
    Args:
        request (HttpRequest): The HTTP request object containing metadata 
                               about the request, including the 'page' query parameter.
    
    Returns:
        HttpResponse: The rendered 'doers_list.html' template displaying the paginated
                      list of doers and pagination controls, or an error message.
    """
    try:
        doers_list = Employee.objects.filter(role='Electrician').order_by('id')
        paginator = Paginator(doers_list, 2)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

    except (PageNotAnInteger, EmptyPage):  
        page_obj = paginator.page(1)

    except Employee.DoesNotExist:
        page_obj = None

    context = {
        'page_obj': page_obj,
        'title': 'Список електриків',
    }
    
    return render(request, 'workflow/doers_list.html', context)


def get_doer_tasks_view(request, doer_id):
    """View to list all tasks for a specific doer.
    
    Args: 
        request (HttpRequest): The HTTP request object containing metadata 
                               about the request, including the 'page' query parameter.
        doer_id (int): ID of requested doer.
    """
    try:
        doer = get_object_or_404(get_user_model(), id=doer_id)
    except Http404:
        return render(request, 'assignment/error_no_doer.html', {
            'message': 'Запит недійсний, тому що не існує такого електрика.',
            'title': 'Неіснуючий електрик',
        })

    tasks = Task.objects.filter(doer=doer)
    paginator = Paginator(tasks, 2)

    try:
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
    except (PageNotAnInteger, EmptyPage):
        page_obj = paginator.page(1)

    context = {
        'page_obj': page_obj,
        'doer': doer,
        'title': f'Завдання для {doer.first_name} {doer.last_name}',
    }
    return render(request, 'workflow/doer_tasks_list.html', context)

workflow/templates/workflow/base_workflow.html
{% extends "task/base_task.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="conainer bg-primary m-2 rounded">
        {% block content_workflow %}
        {% endblock %}
    </div>
{% endblock %}

workflow/templates/workflow/create_task_assignment.html
{% extends "workflow/base_workflow.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content_workflow %}

<div class="col-12 bg-dark rounded">
    <h2 class="text-center text-white my-4 fs-10">{{ title }}</h2>
</div>
<div class="container justify-content-center">
    <div class="row mb-5">
        <div class="col-md-6 col-sm-12 text-white">
        <form method="post" action="">
            {% csrf_token %} 
            {{ form.as_p }}

            <button type="submit" class="btn btn-success">{{ title }}</button>
        </form>
        </div>
    </div>
</div> 

{% endblock %}

workflow/templates/workflow/doer_tasks_list.html
{% extends "workflow/base_workflow.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content_workflow %}

    <div class="col-12 mt-5">
        {% include 'partials/window_history_back.html' %}
    </div>

    <div class="col-12">
        <h4 class="text-center text-white my-3 p-1 bg-dark rounded">{{ title }}</h4>
    </div>

    <div class="container justify-content-center">
        <div class="row mb-5">
            <div class="col-md-6 col-sm-12 text-white">

            {% if page_obj %}    
                <ul class="list-unstyled">
                {% for task in page_obj %} 
                    
                    <li><strong>Створено:</strong></br> {{ task.created_at }}</li>
                    <li class="bg-dark p-2 m-2 rounded">
                        {{ task.task_description }}
                    </li>
                    <li>
                        <strong>
                            Bиконати до:</br>
                            {% if task.deadline %}
                                <span class="text-warning fw-bold">{{ task.deadline }}</span>
                            {% else %}
                                <span class="text-warning fw-bold">Завдання не закінчене</span>
                            {% endif %}
                        </strong>
                    </li>
                    <li>
                        <strong>Статус:</strong></br>
                         <a href="{% url 'task:task_update_status' pk=task.id %}" class="btn btn-success"> 
                        {{ task.get_status_display }}
                        </a> 
                    </li>
                    
                    <hr class="bg-primary mt-3 mb-2" style="border-top: 3px double;">
                {% endfor %}
                </ul>
            </div>
            {% else %}
                <h5 class="bg-info ml-2 p-1 rounded">Завдання немає</h5>
            {% endif %}
        </div>
    </div> 

    {% include "partials/paginator.html" %}

{% endblock %}

workflow/templates/workflow/doers_list.html
{% extends "workflow/base_workflow.html" %}
{% load custom_filters %}

{% block title %}{{ title }}{% endblock %}

{% block content_workflow %}
    
    <div class="mt-5">
        {% include 'partials/window_history_back.html' %}
    </div>
    
    <div class="col-12 bg-info rounded">
        <h2 class="text-center my-4 fs-10">{{ title }}</h2>
    </div>

    <div class="container justify-content-center">
        <div class="row mb-5">
            <div class="col-md-6 col-sm-12 text-white">
                <ul class="list-unstyled">
                    {% for doer in page_obj %}
                        <li>{{ doer.first_name }} {{ doer.last_name }}</li>
                        <li>{{ doer.cell_number|format_phone }}</li>
                        {% if doer.email %}
                            <li>{{ doer.email }}</li>
                        {% else %}
                            <li>Email не вказано</li>
                        {% endif %}
                        <li class="mb-2">
                            {{ doer.admission_group }}</br>
                            <a href="{% url 'users:update_admission_group' doer.id %}"
                            class="text-dark bg-info mb-2 p-1">
                                Оновити групу допуску
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'workflow:doer_tasks' doer.id %}" class="btn btn-success">
                                Завдання
                            <a>
                        </li>
                        <hr class=" bg-white double">
                    {% endfor %}
                    <ul>
                </div>
            </div>
        </div>

    {% include "partials/paginator.html" %}
    
{% endblock %}

workflow/templates/workflow/error_no_doer.html
{% extends "workflow/base_workflow.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="col-12">
        <h4 class="text-center my-4 bg-dark rounded">{{ title }}</h4>
    </div>
    <div class="container justify-content-center">
        <div class="row mb-5">
            <div class="col-md-6 col-sm-12 text-white">

            <p>{{ message }}</p>
            <a href="{% url 'workflow:task_doers_list' %}" class="btn btn-success">
                Назад до Списку електриків
            </a>
            </div>
        </div>
    </div>
{% endblock %}