config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView 

from debug_toolbar.toolbar import debug_toolbar_urls


admin.site.site_header = "Energy Unit's Admin"

urlpatterns = [
    path('admin/', admin.site.urls),

    path(
        '', 
         TemplateView.as_view(template_name='index.html'), 
         name='main_page'
         ),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('work_tower/', include(('work_tower.urls', 'work_tower'), namespace='work_tower')),
    path('task/', include(('task.urls', 'task'), namespace='task')),
    path('workflow/', include(('workflow.urls', 'workflow'), namespace='workflow'),
         ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
  + debug_toolbar_urls()

task/urls.py
from django.urls import path
from .views import (
    DoerTasksListView,
    TaskStatusUpdateView,
    
    get_archived_tasks_view,
    )


app_name = "task"

urlpatterns = [
    path(
        'doer_tasks/<int:doer_id>/', 
        DoerTasksListView.as_view(), 
        name='doer_tasks'
        ),
    path(
        'task_update_status/<int:pk>/', 
        TaskStatusUpdateView.as_view(), 
        name='task_update_status',
        ),
    path('get_archived_tasks/', get_archived_tasks_view, name='get_archived_tasks'),

]

users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordChangeDoneView

from .views import ( 
    user_login_view,
    user_logout_view,
    user_mobile_update_view,
    reset_password_view,
    delete_user_view,
    check_user_view,
    verify_code_view
    )

from .employee_views import ( 
    employee_register_view,
    employee_profile_view,
    get_electricians_view,
    update_employee_admission_group_view, 
    )


app_name = 'users'

urlpatterns = [
    path('register/', employee_register_view, name='register'),
    path('login/', user_login_view, name='login'),
    path('logout/', user_logout_view, name='logout'),

    path('employee_profile/<int:employee_id>/', employee_profile_view, name='employee_profile'),
    path('update_mobile/', user_mobile_update_view, name='update_mobile'),
    path('reset_password/', reset_password_view, name='reset_password'),
    path(
        'password_change_done/', 
         PasswordChangeDoneView.as_view(template_name='users/registration/password_change_done.html'), 
         name='password_change_done'
         ),

    path('delete_account/', delete_user_view, name='delete_account'),

    path('electricians_list', get_electricians_view, name='electricians_list'),

    path(
        'update-admission-group/<int:employee_id>/', 
        update_employee_admission_group_view, 
        name='update_admission_group'),

    path('check_user/', check_user_view, name='check_user'),
    path('verify_code/', verify_code_view, name='verify_code'),
]

users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import get_user_model, authenticate

CustomUser = get_user_model()


class UserLoginForm(forms.Form):
    cell_number = forms.CharField(
        max_length=13,
        label='Номер мобільного',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '+380501234567'
        },
        )
    )
    password = forms.CharField(
        max_length=50,
        label='Пароль',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control', 
            'placeholder': 'Введіть Ваш пароль'
            })
    )


class UserCellUpdateForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', 
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 
                                                                 'placeholder': 'Введіть Ваш пароль'}
                                                        )
                               )

    class Meta:
        model = CustomUser
        fields = ['cell_number',]
        widgets = {
            'cell_number': forms.TextInput(attrs={'class': 'form-control'}),
            }
        labels = {
            'cell_number': 'Номер мобільного',  
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        user = authenticate(username=self.instance.cell_number, password=password)
        if not user:
            raise forms.ValidationError('Невірний пароль.')
        return cleaned_data


class UserPasswordResetForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Старий пароль",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введіть старий пароль'}),
        error_messages = {
            'password_incorrect': 'Введіть правильний пароль.', 
            'required': 'Будь ласка, введіть старий пароль.'
            }
    )
    new_password1 = forms.CharField(
        max_length=50,
        min_length=8,
        label="Новий пароль",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введіть новий пароль'}),
        error_messages={
            'required': 'Будь ласка, введіть новий пароль.',
            'max_length': 'Пароль занадто довгий: не більше 50 символів.',
            'min_length': 'Пароль занадто короткий: не менше 8 символів.',
        }
    )
    new_password2 = forms.CharField(
        label="Новий пароль (підтвердження)",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Підтвердіть новий пароль'}),
        error_messages={
            'required': 'Будь ласка, підтверджте новий пароль.',
            'password_mismatch': 'Новий пароль і підтвердження паролю не співпадають.',
        }
    )

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 and new_password2:
            if new_password1 != new_password2:
                self.add_error('new_password2', 'Паролі не збігаються.')
        return cleaned_data


class UserPasswordCheckForm(forms.Form):
    password = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(attrs={ 
                                        'class': 'form-control', 
                                        'placeholder': 'Введіть пароль'
                                        }
                                    ),
        strip=False,
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_password(self):
        password = self.cleaned_data.get("password")
        if not self.user.check_password(password):
            raise forms.ValidationError("Невірний пароль. Будь ласка, спробуйте ще раз.")
        return password


class UserCredentialsForm(forms.Form):
    """Form to check if a user exists and validate their email."""
    cell_number = forms.CharField(
        max_length=15,
        label="Мобільний номер:",
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '+380501234567'
        },
        ),
    )
    email = forms.EmailField(
        label="Email:",
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введіть Вашу електронну пошту'
        },
        ),
    )

    def clean(self):
        cleaned_data = super().clean()
        cell_number = cleaned_data.get('cell_number')
        email = cleaned_data.get('email')

        if cell_number and email:
            try:
                user = CustomUser.objects.get(cell_number=cell_number)
                if user.email != email:
                    self.add_error('email', 
                                   "Вказаний email не збігається з електронною поштою,\
                                   зареєстрованою для цього номера телефону."
                    )
            except CustomUser.DoesNotExist:
                self.add_error('email', 'Користувача з таким номером телефону не знайдено.')
        else:
            self.add_error('email', 'Будь ласка, введіть номер телефону та електронну пошту')
        return cleaned_data

class VerificationCodeForm(forms.Form):
    email = forms.EmailField(label="Email", required=True)
    verification_code = forms.CharField(label="Verification Code", max_length=6, required=True)

users/views.py
import logging
from django.shortcuts import (
    render, 
    redirect, 
    get_object_or_404,
    )
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (
    login, 
    authenticate, 
    update_session_auth_hash, 
    logout,
    get_user_model,
    get_backends,
    )
from django.core.mail import send_mail
from django.urls import reverse
from django.utils.http import urlencode
from django.http import HttpResponse

from .forms import (
    UserLoginForm,
    UserCellUpdateForm,
    UserCredentialsForm,
    UserPasswordResetForm,
    UserPasswordCheckForm,
    VerificationCodeForm,
    )
from .utils import generate_verification_code, generate_password


logger = logging.getLogger(__name__)

verification_codes = {}

    
def user_login_view(request):
    """ Handle user login.

    Args:
        request (HttpRequest): The HTTP request object containing metadata about the request.

    Returns:
        HttpResponse: Renders the login form on GET request.
                      Redirects to user profile on successful POST request.
    """
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cell_number = form.cleaned_data['cell_number']
            password = form.cleaned_data['password']
            employee = authenticate(request, cell_number=cell_number, password=password)
            if employee is not None:
                login(request, employee)
                url = reverse('users:employee_profile', kwargs={'employee_id': employee.pk})
                return redirect(url)  
            else:
                messages.error(request, 'Неправильний номер мобільного чи пароль.')
    else:
        form = UserLoginForm()
    context = {
        'form': form,
        'title': 'Авторизація',
        'next': request.GET.get('next', '/'),
    }
    return render(request, 'users/registration/login.html', context)



def user_logout_view(request):
    """ Handle user logout.

    Args:
        request (HttpRequest): The HTTP request object containing metadata about the request.

    Returns:
        HttpResponse: Redirects to home page on successful logout.
    """
    logout(request)
    return redirect(reverse('main_page')) 


def user_mobile_update_view(request):
    """ Handle user cell number update.

    Args:
        request (HttpRequest): The HTTP request object containing metadata about the request.

    Returns:
        HttpResponse: Renders the user profile update form on GET request.
                      Redirects to user profile on successful POST request.
    """
    employee = request.user
    
    if request.method == 'POST':
        form = UserCellUpdateForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return redirect('users:employee_profile', employee_id=employee.id)
        else:
            messages.error(request, 'Ваші дані не вдалося оновити. Будь ласка, перевірте пароль.')
    else:
        form = UserCellUpdateForm(instance=employee)
    
    return render(request, 'users/update_mobile.html', {'form': form, 'title': 'Оновити мобільний'})


def reset_password_view(request):
    """ Handle user password change.

    Args:
        request (HttpRequest): The HTTP request object containing metadata about the request.

    Returns:
        HttpResponse: Renders the password change form on GET request.
                      Redirects to user profile on successful POST request.
    """
    if request.method == 'POST':
        form = UserPasswordResetForm(request.user, request.POST)
        if form.is_valid():
            employee = form.save()
            update_session_auth_hash(request, employee)
            
            if employee.pk:  
                return redirect(reverse('users:password_change_done'))
            else:
                messages.error(request, 'Ваш пароль не вдалося оновити.')
    else:
        form = UserPasswordResetForm(request.user)
    return render(request, 'users/registration/password_change.html', {
        'form': form
    }) 


def delete_user_view(request):
    """ Handle user account deletion.

    Args:
        request (HttpRequest): The HTTP request object containing metadata about the request.

    Returns:
        HttpResponse: Renders the delete user form on GET request.
                      Redirects to home page on successful POST request.
    """
    if request.method == 'POST':
        form = UserPasswordCheckForm(request.user, request.POST)
        if form.is_valid():
            user = request.user
            user.delete()
            logout(request)
            messages.success(request, 'Ваш обліковий запис було видалено.')
            return redirect(reverse('users:login'))
    else:
        form = UserPasswordCheckForm(request.user)
    
    return render(request, 'users/delete_user.html', {'form': form, 'title': 'Видалити профіль'})


def check_user_view(request):
    """View to check if a user exists and send a verification code to their email."""
    
    if request.method == 'POST':
        form = UserCredentialsForm(request.POST)
        if form.is_valid():
            cell_number = form.cleaned_data['cell_number']
            email = form.cleaned_data['email']
            
            verification_code = generate_verification_code()

            request.session['verification_code'] = verification_code
            request.session['user_email'] = email
            request.session['user_id'] = get_user_model().objects.get(email=email).id  
            send_mail(
                subject="Ваш код підтвердження",
                message=f"Ваш код підтвердження: {verification_code}",
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[email],
                fail_silently=False,
            )

            return redirect(reverse('users:verify_code'))
        else:
            return render(request, 'users/check_user.html', {'form': form})
    context = {
        'form': UserCredentialsForm(), 
        'title': 'Перевірка користувача',
    }
    return render(request, 'users/check_user.html', context,)


def verify_code_view(request):
    """View to verify the user's code and redirect to their profile."""
    if request.method == 'POST':
        entered_code = request.POST.get('verification_code')
        stored_code = request.session.get('verification_code')
        user_id = request.session.get('user_id')

        if entered_code == str(stored_code):
            user = get_object_or_404(get_user_model(), id=user_id)
            backend = get_backends()[0]  
            user.backend = f"{backend.__module__}.{backend.__class__.__name__}"
            login(request, user)

            password = generate_password()
            raw_password = password
            user.set_password(password)  
            user.save()
            print(raw_password)
            del request.session['verification_code']
            del request.session['user_id']

            return HttpResponse(
                f"<h1 class='text-center'>Ваш пароль: {raw_password} Нікому не передавати!</h1>"
                )
        else:
            return render(
                request,
                'users/verify_code.html',
                {
                    'title': 'Код підтвердження',
                    'error': 'Невірний код підтвердження. Спробуйте ще раз',
                }
            )
    return render(request, 'users/verify_code.html', {'title': 'Код підтвердження'})

users/templates/users/base_users.html
{% extends "base.html" %}
{% load static %}

{% block title %}Користувачі: {% block users_title %}головна{% endblock %}{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'users/css/users_style.css' %}">
    {{ block.super }}
{% endblock %}

{% block header %}{% endblock %}

{% block navbar %}{% endblock %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            {% block users_content %}
                        
            {% endblock %}
        </div>
    </div>
</div>            

{% endblock %}

{% block scripts %}{% endblock scripts %}

users/templates/users/check_user.html
{% extends 'users/base_users.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    
    <div class="container mt-5">
        <h2>{{ title }}</h2>
    </div>

    <div class="bg-primary text-white p-4 m-2 rounded">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">
                Перевірити
            </button>
        </form>
    </div>
{% endblock %}

users/templates/users/delete_user.html
{% extends 'users/base_users.html' %}

{% block title %}{{ title }}{% endblock %}


{% block content %}
  <div class="container mt-5">
    <h2>{{ title }}</h2>
  </div>

  <div class="bg-primary text-white p-4 m-2 rounded">
  
    <p>Ви впевнені що хочете видалити Ваш профіль? Цю дію потім неможливо буде відмінити.</p>

    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}

      <button class="btn btn-danger" type="submit">Підтвердити видалення</button>
      <a class="fw-bold" href="{% url 'users:employee_profile' request.user.id %}">Bідмінити</a>

    </form>
  </div>
{% endblock %}

users/templates/users/electricians_list.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="container bg-primary mt-5 p-2 rounded">

    {% include "partials/window_history_back.html" %}

    <div class="col-12">
        <h4 class="text-center my-2 fs-10">{{ title }}</h4>
    </div>

    <div class="container mb-2">
        <div class="row justify-content-center">
            <div class="col-md-6 col-sm-12 text-white bg-dark rounded">
                {% if page_obj %}
                    {% for electrician in page_obj %} 
                        <ul class="list-unstyled">

                            <li class="text-info">
                                {{ electrician.first_name }} {{ electrician.last_name }}
                            </li>
                            <li>{{ electrician.cell_number }}</li>

                            {% if electrician.email %}
                                <li>{{ electrician.email }}</li>
                            {% else %}
                                <li>Email не вказано</li>
                            {% endif %}

                            <li>
                                <a href="{% url 'users:update_admission_group' electrician.id %}"
                                   class="border border-white border double text-white my-2 p-1 rounded">
                                    {{ electrician.admission_group }}
                                </a>
                            </li>

                            <li>{{ electrician.get_role_display }}</li>
                        </ul>

                        <hr class="w-75 bg-primary mt-3 mb-2" style="border-top: 3px dotted;">
                    {% endfor %}
                {% else %}
                    <p>Електриків не зареєстровано.</p>
                {% endif %}
            </div>
        </div>
    </div> 

    {% include 'partials/paginator.html' %}
</div>

{% endblock %}

users/templates/users/employee_profile.html
{% extends 'users/base_users.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    
    <div class="container mt-5">
        <h2>{{ title }}</h2>
    </div>
    
    <div class="bg-primary text-white p-4 m-2 rounded">
        {% for employee in employees %}
            <h4>{{ employee.first_name }} {{ employee.last_name }}</h4>
            <h6>{{ employee.cell_number }}</h6>
            {% if employee.email %}
                <h6>{{ employee.email }}</h6>
            {% else %}
                <h6>Email: Не вказано</h6>
            {% endif %}
            <h5>{{ employee.admission_group }}</h5>
            <h6>{{ employee.get_role_display }}</h6>
            <hr />
    
        {% endfor %}
    </div>
    
    <div class="d-grid gap-2 d-md-block">
        <a class="btn btn-success" type="button" href="{% url 'users:update_mobile' %}">Оновити mobile</a>
        <a class="btn btn-warning" type="button" href="{% url 'users:reset_password' %}">Змінити пароль</a>
        <a class="btn btn-danger" type="button" href="{% url 'users:delete_account' %}">Видалити профіль</a>
    </div>
    
{% endblock %}

users/templates/users/employee_update_form.html
{% extends 'users/base_users.html' %}
{% load static %}


{% block title %}{{ title }}{% endblock %}

{% block content %}
    
    <div class="container mt-5">
        {% include "partials/window_history_back.html" %}
    </div>

    <div class="container text-center">
        <h3>{{ title }} {{ employee.first_name }} {{ employee.last_name }}</32>
    </div>
    
    <div class="bg-primary text-white p-4 m-2 rounded">
        <form 
            {% comment %} id="update-admission-group-form"  {% endcomment %}
            method="post" 
            {% comment %} action="{% url 'users:admission_group_update' pk=employee.pk %}" {% endcomment %}
            >
            
            {% csrf_token %}
            {{ form.as_p }}
            
            <button type="submit" class="btn btn-success">
                Зберегти
            </button>
        </form>
        <a 
            href="{% url 'users:electricians_list' %}" 
            class="btn btn-warning my-2">
            Скасувати
        </a>
    </div>
    
{% endblock %}

{% block scripts %}
        <script src="{% static 'users/main.js' %}"></script>
{% endblock scripts %}

users/templates/users/update_mobile.html
{% extends 'users/base_users.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h2 class="mt-4">{{ title }}</h2>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid gap-2 d-md-block">
            <button type="submit" class="btn btn-success">{{ title }}</button>
            <a class="fw-bold ml-auto" href="{% url 'users:employee_profile' request.user.pk %}">Назад у профіль</a>
        </div> 
        
    </form>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
{% endblock %}

users/templates/users/verify_code.html
{% extends 'users/base_users.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    
    <div class="container mt-5">
        <h2>{{ title }}</h2>
    </div>

    <div class="bg-primary text-white p-4 m-2 rounded">
        
        {% if error %}
            <p style="color: red;">{{ error }}</p>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <label for="verification_code">код підтвердження:</label>
            <input type="text" name="verification_code" id="verification_code" required>
            <button type="submit">Перевірити</button>
        </form>
    </div>
{% endblock %}