config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView 

from debug_toolbar.toolbar import debug_toolbar_urls


admin.site.site_header = "Energy Unit's Admin"

urlpatterns = [
    path('admin/', admin.site.urls),

    path(
        '', 
         TemplateView.as_view(template_name='index.html'), 
         name='main_page'
         ),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('work_tower/', include(('work_tower.urls', 'work_tower'), namespace='work_tower')),
    path('task/', include(('task.urls', 'task'), namespace='task')),
    path('workflow/', include(('workflow.urls', 'workflow'), namespace='workflow'),
         ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
  + debug_toolbar_urls()

task/urls.py
from django.urls import path
from .views import (
    DoerTasksListView,
    TaskStatusUpdateView,
    
    get_archived_tasks_view,
    )


app_name = "task"

urlpatterns = [
    path(
        'doer_tasks/<int:doer_id>/', 
        DoerTasksListView.as_view(), 
        name='doer_tasks'
        ),
    path(
        'task_update_status/<int:pk>/', 
        TaskStatusUpdateView.as_view(), 
        name='task_update_status',
        ),
    path('get_archived_tasks/', get_archived_tasks_view, name='get_archived_tasks'),

]

work_tower/urls.py
from django.urls import path
from django.views.generic import TemplateView 

from work_tower.views.substation import substations_list_view
from work_tower.views.mcc import substation_mccs_view, mcc_nodes_view
from work_tower.views.node import (
    nodes_list_view, 
    motors_list_view, 
    create_node_motor_view, 
    create_node_view, 
    node_detail_view, 
    show_created_node_view, 
    show_created_node_motor_view, 
    get_level_nodes_view, 
    pre_change_data_view, 
    search_node_view, 
    update_node_motor_view, 
    update_node_view, 
    delete_motor_view, 
    delete_node_view,
)      


app_name = 'work_tower'

urlpatterns = [
    path('', substations_list_view, name='substations'),
    path('substation/<slug:substation_slug>/', substation_mccs_view, name='substation_mccs'),
    path('mcc/<slug:mcc_slug>/', mcc_nodes_view, name='mcc_detail'),

    path('node_list/', nodes_list_view, name='node_list'),
    path('motor_list/', motors_list_view, name='motors_list'),

    path('create_node_motor/', create_node_motor_view, name='create_node_motor'),
    path('create_node/', create_node_view, name='create_node'),

    path('show_created_node/', show_created_node_view, name='show_created_node'),
    path('show_created_node_motor/', show_created_node_motor_view, name='show_created_node_motor'),

    path('get_level_nodes/', get_level_nodes_view, name='get_level_nodes'),

    path('node/<int:node_id>/', node_detail_view, name='node_detail'),
    path('pre_change_data/', pre_change_data_view, name='pre_change_data'),

    path('search_node/', search_node_view, name='search_node'),
    path('update_motor/', update_node_motor_view, name='update_motor'),
    path('update_node/', update_node_view, name='update_node'),
    path(
        'updated_motor_message/', 
         TemplateView.as_view(template_name='work_tower/messages/updated_motor_message.html'), 
         name='updated_motor_message'
         ),
    path(
        'updated_node_message/', 
         TemplateView.as_view(template_name='work_tower/messages/updated_node_message.html'), 
         name='updated_node_message'
         ),

    path('delete_motor/', delete_motor_view, name='delete_motor'),
    path('delete_node/', delete_node_view, name='delete_node'),
    path(
        'deleted_motor_message/', 
         TemplateView.as_view(template_name='work_tower/messages/deleted_motor_message.html'), 
         name='deleted_motor_message'
         ),
    path(
        'deleted_node_message/', 
         TemplateView.as_view(template_name='work_tower/messages/deleted_node_message.html'), 
         name='deleted_node_message'
         ),
]

work_tower/forms.py
from django import forms
from work_tower.models.node import Node, NodeMotor


class NodeCreationForm(forms.ModelForm):
    """Form for creating a Node."""

    class Meta:
        model = Node
        fields = ['name', 'index', 'level', 'motor', 'mcc']
        widgets = {
            'name': forms.Select(attrs={'class': 'form-control'}),
            'index': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '1_1_1_1_1'}),
            'level': forms.Select(attrs={'class': 'form-control'}),
            'motor': forms.Select(attrs={'class': 'form-control'}),
            'mcc': forms.Select(attrs={'class': 'form-control'}),
        }
       
        labels = {  
            'name': 'Назва',
            'index': 'Індекс',
            'level': 'Відмітка',
            'motor': 'Мотор',
            'mcc': 'MCC'
        }

class NodeMotorCreationForm(forms.ModelForm):
    """Form for creating a motor for the Node."""
    
    class Meta:
        model = NodeMotor
        fields = ['power', 'round_per_minute', 'connection', 'amperage',]
       
        labels = {  
            'power': 'Потужність',
            'round_per_minute': 'Обороти на хвилину',
            'connection': 'Тип з\'єднання',
            'amperage': 'Сила струму',
        }

work_tower/views/mcc.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from work_tower.models.mcc import MotorControlCenter as MCC
from work_tower.models.substation import Substation
from work_tower.models.node import Node


def substation_mccs_view(request, substation_slug):
    """
    Retrieve and display Motor Control Centers (MCCs) associated with a specific substation.

    Args:
        request (HttpRequest): The HTTP request object.
        substation_slug (str): The slug of the substation whose MCCs are to be displayed.

    Returns:
        HttpResponse: A rendered HTML response with the substation details and its associated MCCs.
    """
    substation = get_object_or_404(Substation, slug=substation_slug)
    mccs = MCC.objects.filter(substation=substation)
    
    context = {
        'substation': substation,
        'mccs': mccs
    }
    return render(request, 'work_tower/substation_mccs.html', context)


def mcc_nodes_view(request, mcc_slug):
    """
    Retrieve and display details of a specific Motor Control Center (MCC) and its associated nodes.

    Args:
        request (HttpRequest): The HTTP request object.
        mcc_slug (str): The slug of the MCC whose details and associated nodes are to be displayed.

    Returns:
        HttpResponse: A rendered HTML response with the MCC details and its associated nodes.
    """
    mcc = get_object_or_404(MCC, slug=mcc_slug)
    nodes = Node.objects.filter(mcc=mcc)
    
    context = {
        'mcc': mcc, 
        'nodes': nodes
        }
    return render(request, 'work_tower/mcc_detail.html', context)

work_tower/views/node.py
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.db.models.deletion import ProtectedError

from django.http import Http404

from work_tower.forms import NodeCreationForm, NodeMotorCreationForm
from work_tower.models.node import Node, NodeMotor
from work_tower.models.work_tower import WorkTowerLevel


def nodes_list_view(request):
    nodes = Node.objects.all()
    return render(request, 'work_tower/node/nodes_list.html', {'nodes': nodes})


def motors_list_view(request):      
    """
    Displays a paginated list of NodeMotor instances. If an error occurs while
    fetching motors or pagination fails, the error is handled gracefully.
    
    Args:
        request (HttpRequest): The HTTP request object containing metadata 
                               about the request, including the 'page' query parameter.
    
    Returns:
        HttpResponse: The rendered 'motors_list.html' template displaying the paginated
                      list of motors and pagination controls, or an error message.
    """
    try:
        motors = NodeMotor.objects.all()
        paginator = Paginator(motors, 2)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

    except (PageNotAnInteger, EmptyPage):  
        page_obj = paginator.page(1)

    except NodeMotor.DoesNotExist:
        page_obj = None

    context = {
        'motors': motors,
        'page_obj': page_obj,
    }
    return render(request, 'work_tower/node/motors_list.html', context)



def create_node_motor_view(request):    
    """
    Handles the creation of a new NodeMotor instance.

    Args:
        request (HttpRequest): The HTTP request object containing metadata and form data.

    Returns:
        HttpResponse: The rendered template with the form for GET requests, or a redirect 
                      to the 'node:create_node' URL after a successful form submission.
    """
    if request.method == 'POST':
        form = NodeMotorCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('work_tower:show_created_node_motor')  
        else:
            print(form.errors)
    else:
        form = NodeMotorCreationForm()
    
    return render(request, 'work_tower/node/create_node_motor.html', {'form': form})


def create_node_view(request):      
    """
    Handles the creation of a new Node instance.

    Args:
        request (HttpRequest): The HTTP request object containing metadata and form data.

    Returns:
        HttpResponse: The rendered template with the form for GET requests, or a redirect 
                      to the 'node:node_list' URL after a successful form submission.
    """
    if request.method == 'POST':
        form = NodeCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('work_tower:show_created_node')  
    else:
        form = NodeCreationForm()

    return render(request, 'work_tower/node/create_node.html', {'form': form})


def show_created_node_motor_view(request):  
    """
    Displays a success message after a successful NodeMotor creation.

    Args:
        request (HttpRequest): The HTTP request object containing metadata about the request.

    Returns:
        HttpResponse: The rendered template displaying the success message or an appropriate message.
    """
    last_node_motor = NodeMotor.objects.last()
    
    if last_node_motor is None:
        message = "Двигун не був створений."
    else:
        message = ""  

    return render(request, 'work_tower/node/show_created_node_motor.html', {
        'last_node_motor': last_node_motor,
        'message': message
    })


def show_created_node_view(request):        
    """
    Displays a success message after a successful Node creation.

    Args:
        request (HttpRequest): The HTTP request object containing metadata about the request.

    Returns:
        HttpResponse: The rendered template displaying the success message.
    """

    last_node = Node.objects.last()
    return render(request, 'work_tower/node/show_created_node.html', {'last_node': last_node})


def node_detail_view(request, node_id):     
    """
    Displays the details of a specific Node instance.

    Args:
        request (HttpRequest): The HTTP request object containing metadata about the request.
        node_id (int): The ID of the Node instance to be retrieved.

    Returns:
        HttpResponse: The rendered template displaying the details of the Node and its 
                      associated NodeMotor.
    """
    try:
        node = get_object_or_404(Node, id=node_id)
        motor = node.motor

    except Http404:
        return render(request, 'work_tower/errors/Http404.html')

    context = {
        'node': node,
        'motor': motor
    }
    return render(request, 'work_tower/node/node_detail.html', context)


def search_node_view(request):      
    """
    View to search for a Node instance by its index and display its information.

    Args:
        request (HttpRequest): The HTTP request object containing metadata about the request.

    Returns:
        HttpResponse: The rendered template displaying the details of the Node.
    """
    if request.method == 'POST':
        index = request.POST.get('index')

        if not index:
            return render(
                request, 
                'work_tower/node/search_node_form.html', 
                {'error': 'Введіть, буль ласка, індекс.'}
                )

        try:
            node = Node.objects.get(index=index)
            motor = node.motor
            return render(
                request, 
                'work_tower/node/search_node_form.html', 
                {'node': node, 'motor': motor,}
                )

        except Node.DoesNotExist:
            return render(
                request, 
                'work_tower/node/search_node_form.html', 
                {'error': f'Вузол з індексом "{index}" не знайдено.'}
                )

    return render(request, 'work_tower/node/search_node_form.html')


def get_level_nodes_view(request):      
    """
    Displays a list of Node instances filtered by the selected WorkTowerLevel.

    Args:
        request (HttpRequest): The HTTP request object containing metadata about the request.

    Returns:
        HttpResponse: The rendered 'nodes_by_level.html' template displaying the filtered nodes.
    """
    nodes = None
    selected_level = None
    error = None

    if request.method == 'POST':
        level_id = request.POST.get('level')
        if not level_id: 
            error = 'Введіть, буль ласка, відмітку.'
        else:
            try:
                selected_level = get_object_or_404(WorkTowerLevel, id=level_id)
                nodes = Node.objects.filter(level=selected_level)

                if not nodes.exists():  
                    error = f'На відмітці "{selected_level.level}" вузлів немає.'

            except WorkTowerLevel.DoesNotExist:
                error = f'Рівень відмітки "{level_id}" не знайдено.'

    levels = WorkTowerLevel.objects.all()

    context = {
        'levels': levels,
        'nodes': nodes,
        'selected_level': selected_level,
        'error': error,  
    }

    return render(request, 'work_tower/node/level_nodes.html', context)



def pre_change_data_view(request):      
    """
    Displays the endpoints to change the data of the NodeMotor and Node instances.

    Args:
        request (HttpRequest): The HTTP request object containing metadata about the request.

    Returns:
        HttpResponse: The rendered template displaying the buttons to change the data in database.
    """

    return render(request, 'work_tower/node/pre_change_data.html',)


def update_node_motor_view(request):        
    """
    Handles the NodeMotor instance updating with the provided form data.

    Args:
        request (HttpRequest): The HTTP request object containing metadata about the request.

    Returns:
        HttpResponse: The rendered template displaying the updated details of the NodeMotor.
    """
    if request.method == 'POST':
        power = request.POST.get('power')
        
        if not power:
            return render(
                request, 
                'work_tower/node/update_motor_form.html', 
                {'error': 'Введіть, буль ласка, потужність.'}
                )
        try:
            power = float(power)
            motor_id = request.POST.get('motor_id')

            if 'update' in request.POST:
                try:
                    motor = NodeMotor.objects.get(id=motor_id)
                except NodeMotor.DoesNotExist:
                    return render(
                        request, 
                        'work_tower/node/update_motor_form.html', 
                        {'error': f'Двигун з ID {motor_id} не знайдено.'},
                        )
                
                form = NodeMotorCreationForm(request.POST, instance=motor)
                if form.is_valid():
                    form.save()
                    return redirect('node:updated_motor_message')
                else:
                    return render(
                        request, 
                        'work_tower/node/update_motor_form.html', 
                        {'form': form, 'motor': motor},
                        )

            motor = NodeMotor.objects.filter(power=power).first()
            if motor is None:
                return render(
                    request, 
                    'work_tower/node/update_motor_form.html', 
                    {'error': f'Не знайдено двигун з потужністю {power}.'},
                    )

            form = NodeMotorCreationForm(instance=motor)
            return render(
                request, 

work_tower/views/substation.py
from django.shortcuts import render

from work_tower.models.substation import Substation


def substations_list_view(request):
    """
    Retrieve and display a list of all substations.
    
    Args:
        request (HttpRequest): The HTTP request object. It contains metadata about 
                               the request and is passed to the view function.

    Returns:
        HttpResponse: The rendered HTML page as a response, using the 'substation/base.html' 
                      template with the context containing all `Substation` objects.
    """
    substations = Substation.objects.all()
    context={'substations': substations}

    return render(
        request, 
        'work_tower/base_tower.html', 
        context,
        )

work_tower/templates/work_tower/node/create_node.html
{% extends "work_tower/base_tower.html" %}

{% block title %}Додати вузол{% endblock %}

{% block content_area %}

    {% include "partials/window_history_back.html" %}
    
    <div class="col-12">
        <h2 class="text-center my-4 fs-10">Додати вузол</h2>
    </div>
    <div class="container justify-content-center">
        <div class="row mb-5">
            <div class="col-md-6 col-sm-12 text-white">
            <form method="post" action="">
                {% csrf_token %} 
                {{ form.as_p }}

                <button type="submit">Додати вузол</button>
            </form>
            </div>
        </div>
    </div> 

{% endblock %}

work_tower/templates/work_tower/node/delete_node.html
{% extends "work_tower/base_tower.html" %}

{% block title %}Видалити вузол{% endblock %}

{% block content_area %}

    {% include "partials/window_history_back.html" %}
    
    <div class="col-12">
        <h4 class="text-center my-4 fs-10">Сторінка видалення вузла</h4>
    </div>

    <div class="container mb-2">
        <div class="row justify-content-center">
            <div class="col-md-6 col-sm-12 text-white bg-dark p-2 rounded">

                {% if error %}
                    <h5 class="text-primary ">{{ error }}</h5>
                {% endif %}

                {% if success %}
                    <p class="text-primary">{{ success }}</p>
                {% endif %}

                <form method="post">
                    {% csrf_token %}
                    <label for="index">Індекс вузла:</label>
                    <input type="text" name="index" id="index" placeholder="Введіть індекс вузла"
                           class="mb-3">
                    <button type="submit">Видалити вузол</button>
                </form>

            </div>
        </div>
    </div>   
    
{% endblock %}

work_tower/templates/work_tower/node/delete_node_motor.html
{% extends "work_tower/base_tower.html" %}

{% block title %}Видалити двигун{% endblock %}

{% block content_area %}
    
    {% include "partials/window_history_back.html" %}
    
    <div class="col-12">
        <h4 class="text-center my-4 fs-10">Сторінка видалення двигуна</h4>
    </div>

    <div class="container mb-2">
        <div class="row justify-content-center">
            <div class="col-md-6 col-sm-12 text-white bg-dark p-2 rounded">

                {% if error %}
                    <h5 class="text-primary" style="color: red;">{{ error }}</h5>
                {% endif %}

                {% if success %}
                    <p style="color: green;">{{ success }}</p>
                {% endif %}

                <form method="post">
                    {% csrf_token %}
                    <label for="power">Потужність (кВт):</label>
                    <input type="text" name="power" id="power" placeholder="Введіть потужність двигуна"
                           class="mb-3">
                    <button type="submit">Видалити двигун</button>
                </form>

            </div>
        </div>
    </div>   
    
{% endblock %}

work_tower/templates/work_tower/node/index_form.html
<form method="POST">
    {% csrf_token %}
    {% if not node %}
    <div class="mb-3">
        <label for="index" class="form-label">Введіть індекс вузла:</label>
        <input type="text" class="form-control" name="index" id="index"  value="{{ form.name.value }}">
        <button type="submit" class="btn btn-dark mt-2">Знайти вузол</button>
    </div>
    {% endif %}
</form>

{% if error %}
    <p style="color: red;">{{ error }}</p>
{% endif %}

work_tower/templates/work_tower/node/level_nodes.html
{% extends "work_tower/base_tower.html" %}

{% block title %}Знайти вузли{% endblock %}

{% block content_area %}

    {% include "partials/window_history_back.html" %}
    
    <div class="col-12">
        <h4 class="text-center my-4 fs-10">Виберіть потрібну відмітку.</h4>
    </div>

    <div class="container mb-2">
        <div class="row justify-content-center">
            <div class="col-md-6 col-sm-12 text-white bg-dark p-2 rounded">
                
                {% if error %}
                <p style="font-weight: bold;" class="text-primary">{{ error }}</p>
                {% endif %}

                <form method="post">
                    {% csrf_token %}
                    <label for="level">Відмітка:</label>
                    <select name="level" id="level">
                        <option value="">--Виберіть відмітку--</option>
                        {% for level in levels %}
                            <option value="{{ level.id }}"
                                {% if selected_level and level.id == selected_level.id %}selected{% endif %}>
                                {{ level.level }} 
                            </option>
                        {% endfor %}
                    </select>
                    <button type="submit">Знайти вузли</button>
                </form>

                {% if nodes %}
                    <h5>Вузли на відмітці {{ selected_level.level }} м:</h5>
                    <ul>
                        {% for node in nodes %}
                            <li>{{ node.name }} {{ node.index }} - {{ node.motor }}кВт</li>
                        {% endfor %}
                    </ul>
                {% endif %}

            </div>
        </div>
    </div> 

{% endblock %} 

work_tower/templates/work_tower/node/motors_list.html
{% extends "work_tower/base_tower.html" %}

{% block title %}Список двигунів{% endblock %}

{% block content_area %}

    {% include "partials/window_history_back.html" %}

    <div class="col-12">
        <h4 class="text-center my-4 fs-10">Список двигунів</h4>
    </div>

    <div class="container mb-2">
        <div class="row justify-content-center">
            <div class="col-md-6 col-sm-12 text-white bg-dark rounded">
                {% if page_obj %}
                    {% for motor in page_obj %} 
                        <ul>
                            <li class="text-info"><strong>Потужнісь: </strong> {{ motor.power }}кВт.</li>
                            <li><strong>Об. / хв.:</strong> {{ motor.round_per_minute }}</li>
                            <li><strong>Тип з'єднання: </strong> {{ motor.connection }}</li>
                            <li><strong>І, номінальне:</strong> {{ motor.amperage }}A</li>
                        </ul>
                        <hr class="w-75 bg-primary mt-3 mb-2" style="border-top: 3px dotted;">
                    {% endfor %}
                {% else %}
                    <p>Двигунів немає.</p>
                {% endif %}
            </div>
        </div>
    </div> 

    {% include 'partials/paginator.html' %}

{% endblock %} 

work_tower/templates/work_tower/node/node_detail.html
{% extends "work_tower/base_tower.html" %}

{% block title %}{{ node.name }} {{ node.index }}{% endblock %}

{% block content_area %}

    {% include "partials/window_history_back.html" %}

    <div class="col-12">
        <h3 class="text-center my-4 fs-10">{{ node.name }} {{ node.index }}</h3>
    </div>
    <div class="container">
        <div class="row mb-5 justify-content-center">
            <div class="col-md-6 col-sm-12 text-white bg-dark rounded">
             
                <p><strong>Знаходиться на відм. </strong> {{ node.level }} м.</p>
                <p><strong>MCC:</strong> {{ node.mcc }}</p>
                
                {% if motor %}
                    <h4>Двигун вузла</h4>
                    <p><strong>Потужнісь: </strong> {{ motor.power }} кВт.</p>
                    <p><strong>Об. / хв.:</strong> {{ motor.round_per_minute }}</p>
                    <p><strong>Тип з'єднання: </strong> {{ motor.connection }}</p>
                    <p><strong>І, номінальне:</strong> {{ motor.amperage }}A</p>
                {% elif error %}
                    <p style="color:red;">{{ error }}</p>
                {% else %}
                    <p>Параметри двигуна не вказано.</p>
                {% endif %}
                    
            </div>
        </div>
    </div> 

{% endblock %}

work_tower/templates/work_tower/node/nodes_list.html
{% extends "work_tower/base_tower.html" %}

{% block title %}Список вузлів{% endblock %}

{% block content_area %}

    {% include "partials/window_history_back.html" %}
    
    <div class="col-12">
        <h4 class="text-center my-4 fs-10">Список вузлів</h4>
    </div>
    <div class="container justify-content-center">
        <div class="row mb-5">
            <div class="col-md-6 col-sm-12 text-white">
            
                {% for node in nodes %} 
                    <p>{{ node.name }} {{ node.index }}({{ node.mcc }})</p>
                {% endfor %}
            </div>
        </div>
    </div> 

{% endblock %}

work_tower/templates/work_tower/node/pre_change_data.html
{% extends "work_tower/base_tower.html" %}

{% block title %}Внесення змін{% endblock %}

{% block content_area %}

    {% include "partials/window_history_back.html" %}
    
    <div class="col-12">
        <h3 class="text-center my-4 fs-10">Виберіть опцію</h3>
    </div>
    <div class="container text-uppercase">
        <div class="row mb-5 justify-content-center">
            <div class="col-md-6 col-sm-12 bg-white rounded">
             
                <p><a href="{% url 'work_tower:create_node_motor' %}"> Додати двигун </a></p>
                <p><a href="{% url 'work_tower:create_node' %}"> Додати вузол </a></p>
                <p><a href="{% url 'work_tower:update_motor' %}">Оновити двигун</a></p>
                <p><a href="{% url 'work_tower:update_node' %}">Оновити вузол</a></p>       
                <p><a href="{% url 'work_tower:delete_motor' %}">Видалити двигун</a></p>  
                <p><a href="{% url 'work_tower:delete_node' %}">Видалити вузол</a></p> 

            </div>
        </div>
    </div> 

{% endblock %}

work_tower/templates/work_tower/node/search_node_form.html
{% extends "work_tower/base_tower.html" %}

{% block title %}Знайти вузол{% endblock %}

{% block content_area %}

    {% include "partials/window_history_back.html" %}

    <div class="col-12">
        <h4 class="text-center text-uppercase color2 my-4 fs-10">
            Знайти вузол
        </h4>
    </div>
    
    <div class="container justify-content-center">
        <div class="row mb-5">
            <div class="col-md-6 col-sm-12 text-white">

                {% include "work_tower/node/index_form.html" %} 
                
                <div class="bg-dark rounded mt-3">
                {% if node %}
                    <h3 class="">{{ node.name }} {{ node.index }}</h3>
                    <ul>
                        <li><strong>Знаходиться на відм. </strong> {{ node.level }}</li>
                        <li><strong>MCC:</strong> {{ node.mcc }}</li>

                        {% if motor %}
                        <li><strong>Потужнісь: </strong> {{ motor.power }} кВт.</li>
                        <li><strong>Об. / хв.:</strong> {{ motor.round_per_minute }}</li>
                        <li><strong>Тип з'єднання: </strong> {{ motor.connection }}</li>
                        <li><strong>І, номінальне:</strong> {{ motor.amperage }}A</li>
                        {% endif %}
                    </ul>
                {% endif %}
                </div>
            
            </div>
        </div>
    </div> 

{% endblock %}

work_tower/templates/work_tower/node/show_created_node.html
{% extends "work_tower/base_tower.html" %}

{% block title %}Вузол створено{% endblock %}

{% block content_area %}
    <div class="col-12">
        <h4 class="text-center m-5 p-2 bg-dark rounded">
            Вузол "{{ last_node }}" успішно додано.
        </h4>
    </div>
    
{% endblock %}

work_tower/templates/work_tower/node/show_created_node_motor.html
{% extends "work_tower/base_tower.html" %}

{% block title %} Додати двигун {% endblock %}

{% block content_area %}
    <div class="col-12">

        <p>{{ message }}</p>

        {% if last_node_motor %}
            <h4 class="text-center m-5 p-2 bg-dark rounded">
                Двигун потужністю {{ last_node_motor }}кВт успішно додано.
            </h4>
        {% endif %}
        
    </div>
    
{% endblock %}

work_tower/templates/work_tower/node/update_node_form.html
{% extends "work_tower/base_tower.html" %}

{% block title %}Оновити вузол{% endblock %}

{% block content_area %}

    {% include "partials/window_history_back.html" %}

    <div class="col-12">
        <h4 class="text-center text-uppercase my-4 fs-10">
            Оновити вузол
        </h4>
    </div>
    <div class="container justify-content-center">
        <div class="row mb-5">
            <div class="col-md-6 col-sm-12 text-white">

                {% include "work_tower/node/index_form.html" %} 
                
                {% if node %}
                    <h5 class="text-center text-uppercase my-4">
                        Оновити дані вузла ({{ node.index }})
                    </h5>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" name="update" class="btn btn-dark">Оновити</button>
                    </form>

                    {% if error %}
                        <p>{{ error }}</p>
                    {% endif %}
                {% endif %}
            
            </div>
        </div>
    </div> 

{% endblock %}